name: smax
channels:
  - anaconda
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - absl-py=1.4.0=py38h06a4308_0
  - alsa-lib=1.2.10=hd590300_0
  - antlr-python-runtime=4.9.3=pyhd8ed1ab_1
  - aom=3.6.1=h59595ed_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attr=2.5.1=h166bdaf_1
  - attrs=23.1.0=py38h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=openblas
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2023.08.22=h06a4308_0
  - cairo=1.16.0=h0c91306_1017
  - certifi=2023.7.22=py38h06a4308_0
  - cffi=1.15.1=py38h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - chex=0.1.7=pyhd8ed1ab_0
  - click=8.0.4=py38h06a4308_0
  - cloudpickle=2.2.1=py38h06a4308_0
  - colorama=0.4.6=py38h06a4308_0
  - comm=0.1.2=py38h06a4308_0
  - contourpy=1.0.5=py38hdb19cb5_0
  - cryptography=41.0.3=py38h130f0dd_0
  - cuda-nvcc=12.2.140=0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dav1d=1.2.1=h5eee18b_0
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.6.7=py38h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - dm-env=1.6=pyhd8ed1ab_0
  - dm-tree=0.1.7=py38h6a678d5_1
  - docker-pycreds=0.4.0=pyhd3eb1b0_0
  - dotmap=1.3.30=pyhd8ed1ab_0
  - etils=1.4.1=pyhd8ed1ab_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.5.0=h6a678d5_0
  - fastcache=1.1.0=py38h7b6447c_0
  - filelock=3.9.0=py38h06a4308_0
  - flask=2.2.2=py38h06a4308_0
  - flask-cors=3.0.10=pyhd3eb1b0_0
  - fluidsynth=2.3.4=h7741c18_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - gettext=0.21.1=h27087fc_0
  - gitdb=4.0.7=pyhd3eb1b0_0
  - gitpython=3.1.30=py38h06a4308_0
  - glfw=3.3.8=hd590300_1
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py38heeb90bb_0
  - graphite2=1.3.14=h295c915_1
  - grpcio=1.42.0=py38hce63b2e_0
  - gym-notices=0.0.8=pyhd8ed1ab_0
  - harfbuzz=8.2.1=h3d44ed6_0
  - icu=73.2=h59595ed_0
  - idna=3.4=py38h06a4308_0
  - importlib_metadata=6.0.0=hd3eb1b0_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - ipykernel=6.25.2=pyh2140261_0
  - ipython=8.12.2=py38h06a4308_0
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jack=1.9.22=h7c63dc7_2
  - jaxopt=0.8=pyhd8ed1ab_0
  - jedi=0.18.1=py38h06a4308_1
  - jinja2=3.1.2=py38h06a4308_0
  - jupyter_client=8.1.0=py38h06a4308_0
  - jupyter_core=5.3.0=py38h06a4308_0
  - kiwisolver=1.4.4=py38h6a678d5_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.15=h7f713cb_2
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=4.0.0=h27087fc_0
  - libabseil=20230125.3=cxx17_h59595ed_0
  - libavif16=1.0.1=h87da1f6_2
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcap=2.69=h0f662aa_0
  - libccd-double=2.1=h59595ed_3
  - libdb=6.2.32=h6a678d5_1
  - libdeflate=1.19=hd590300_0
  - libffi=3.4.4=h6a678d5_0
  - libflac=1.4.3=h59595ed_0
  - libgcc-ng=13.2.0=h807b86a_2
  - libgcrypt=1.10.1=h166bdaf_0
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.0=hebfc3b9_0
  - libgpg-error=1.47=h71f35ed_0
  - libiconv=1.17=h166bdaf_0
  - libjpeg-turbo=2.1.5.1=hd590300_1
  - libmad=0.15.1b=h0b41bf4_1001
  - libmujoco=2.3.7=hd8909ca_0
  - libogg=1.3.5=h27cfd23_1
  - libopenblas=0.3.21=h043d6bf_0
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=3.20.3=he621ea3_0
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=13.2.0=h7e041cc_2
  - libsystemd0=254=h3516f8a_0
  - libtiff=4.6.0=h29866fb_1
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h7b6447c_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libzlib=1.2.13=hd590300_5
  - llvm-openmp=14.0.6=h9e868ea_0
  - lodepng=20220109=h924138e_0
  - lz4-c=1.9.4=h6a678d5_0
  - markdown-it-py=2.2.0=py38h06a4308_1
  - markupsafe=2.1.1=py38h7f8727e_0
  - matplotlib-base=3.7.2=py38h1128e8f_0
  - matplotlib-inline=0.1.6=py38h06a4308_0
  - mdurl=0.1.0=py38h06a4308_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpg123=1.32.2=h59595ed_0
  - mpmath=1.3.0=py38h06a4308_0
  - msgpack-python=1.0.3=py38hd09550d_0
  - mujoco-python=2.3.7=py38h498f2f9_0
  - munkres=1.1.4=py_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=py38h06a4308_0
  - networkx=3.1=py38h06a4308_0
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - numpy-base=1.24.3=py38h1e6e340_0
  - omegaconf=2.3.0=pyhd8ed1ab_0
  - openjpeg=2.5.0=h488ebb8_3
  - openssl=1.1.1w=h7f8727e_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - optax=0.1.4=py38h06a4308_0
  - opusfile=0.12=hae46d1a_2
  - packaging=23.1=py38h06a4308_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pathtools=0.1.2=pyhd3eb1b0_1
  - pcre2=10.40=hc3806b6_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=23.2.1=py38h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - platformdirs=3.10.0=py38h06a4308_0
  - pluggy=1.0.0=py38h06a4308_1
  - pooch=1.7.0=py38h06a4308_0
  - portaudio=19.6.0=h7b6447c_4
  - portmidi=2.0.4=h7c63dc7_2
  - prompt-toolkit=3.0.36=py38h06a4308_0
  - psutil=5.9.0=py38h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pulseaudio-client=16.1=hb77b528_5
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py=1.11.0=pyhd3eb1b0_0
  - pybind11-abi=4=hd3eb1b0_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pygame=2.5.2=py38h3762873_0
  - pyglfw=2.6.2=py38h578d9bd_1
  - pygments=2.15.1=py38h06a4308_1
  - pyopengl=3.1.1a1=py38h06a4308_0
  - pyopenssl=23.2.0=py38h06a4308_0
  - pyparsing=3.0.9=py38h06a4308_0
  - pysocks=1.7.1=py38h06a4308_0
  - pytest=7.1.2=py38h06a4308_0
  - python=3.8.16=h7a1cb2a_3
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytinyrenderer=0.0.13=py38h0814e1a_1
  - pytorch=2.0.1=cpu_py38hab5cca8_0
  - pyyaml=6.0=py38h5eee18b_1
  - pyzmq=25.1.0=py38h6a678d5_0
  - qhull=2020.2=hdb19cb5_2
  - rav1e=0.6.6=he8a937b_2
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py38h06a4308_0
  - rich=13.3.5=py38h06a4308_0
  - sdl2=2.28.4=h77f46ba_0
  - sdl2_image=2.6.3=h17907d7_3
  - sdl2_mixer=2.6.3=h8830914_1
  - sdl2_ttf=2.20.2=ha14f88b_2
  - sentry-sdk=1.9.0=py38h06a4308_0
  - setproctitle=1.2.2=py38h27cfd23_1004
  - setuptools=68.0.0=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - smmap=4.0.0=pyhd3eb1b0_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - svt-av1=1.7.0=h59595ed_0
  - sympy=1.5.1=py38_0
  - tinyxml2=9.0.0=h9c3ff4c_2
  - tk=8.6.12=h1ccaba5_0
  - tomli=2.0.1=py38h06a4308_0
  - toolz=0.12.0=py38h06a4308_0
  - tornado=6.3.2=py38h5eee18b_0
  - tqdm=4.65.0=pyhd8ed1ab_1
  - traitlets=5.7.1=py38h06a4308_0
  - trimesh=3.9.35=pyh6c4a22f_0
  - typing-extensions=4.7.1=py38h06a4308_0
  - typing_extensions=4.7.1=py38h06a4308_0
  - urllib3=1.26.16=py38h06a4308_0
  - wandb=0.15.4=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - werkzeug=2.2.3=py38h06a4308_0
  - wheel=0.41.2=py38h06a4308_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.6=h8ee46fc_0
  - xorg-libxcursor=1.2.0=h0b41bf4_1
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxinerama=1.1.5=h27087fc_0
  - xorg-libxrandr=1.5.2=h7f98852_1
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-randrproto=1.5.0=h7f98852_1001
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h27cfd23_1007
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hc292b87_0
  - pip:
      - arrow==1.3.0
      - boto3==1.28.62
      - botocore==1.31.62
      - bravado==11.0.3
      - bravado-core==6.1.0
      - brax==0.9.2
      - cached-property==1.5.2
      - contextlib2==21.6.0
      - dataclasses==0.6
      - distrax==0.1.3
      - docopt==0.6.2
      - evosax==0.1.4
      - farama-notifications==0.0.4
      - flatten-dict==0.4.2
      - flax==0.7.2
      - fqdn==1.5.1
      - future==0.18.3
      - gast==0.5.4
      - gym==0.26.2
      - gymnasium==0.28.1
      - gymnax==0.0.6
      - hydra-core==1.3.2
      - id-mava==0.2.0
      - imageio==2.31.1
      - importlib-metadata==6.6.0
      - isoduration==20.11.0
      - jax==0.4.13
      - jax-jumpy==1.0.0
      - jaxlib==0.4.13+cuda12.cudnn89
      - jmespath==1.0.1
      - jsonpickle==3.0.2
      - jsonpointer==2.4
      - jsonref==1.1.0
      - jsonschema==4.19.1
      - jsonschema-specifications==2023.7.1
      - jumanji==0.3.1
      - ml-collections==0.1.1
      - ml-dtypes==0.2.0
      - monotonic==1.6
      - munch==2.5.0
      - neptune==1.8.0
      - neptune-sacred==1.0.1
      - numpy==1.22.4
      - nvidia-cublas-cu12==12.2.5.6
      - nvidia-cuda-cupti-cu12==12.2.142
      - nvidia-cuda-nvcc-cu12==12.2.140
      - nvidia-cuda-nvrtc-cu12==12.2.140
      - nvidia-cuda-runtime-cu12==12.2.140
      - nvidia-cudnn-cu12==8.9.4.25
      - nvidia-cufft-cu12==11.0.8.103
      - nvidia-cusolver-cu12==11.5.2.141
      - nvidia-cusparse-cu12==12.1.2.141
      - nvidia-nvjitlink-cu12==12.2.140
      - oauthlib==3.2.2
      - orbax-checkpoint==0.2.3
      - pandas==2.0.2
      - pettingzoo==1.23.1
      - pillow==9.5.0
      - pkgutil-resolve-name==1.3.10
      - protobuf==4.23.3
      - py-cpuinfo==9.0.0
      - pyjwt==2.8.0
      - pytz==2023.3
      - referencing==0.30.2
      - requests-oauthlib==1.3.1
      - rfc3339-validator==0.1.4
      - rfc3987==1.3.8
      - rpds-py==0.10.4
      - s3transfer==0.7.0
      - sacred==0.8.4
      - safetensors==0.3.3
      - scipy==1.10.1
      - seaborn==0.12.2
      - simplejson==3.19.2
      - swagger-spec-validator==3.0.3
      - tensorboard-logger==0.1.0
      - tensorboardx==2.6.1
      - tensorflow-probability==0.20.1
      - tensorstore==0.1.45
      - types-python-dateutil==2.8.19.14
      - tzdata==2023.3
      - uri-template==1.3.0
      - webcolors==1.13
      - websocket-client==1.6.3
      - wrapt==1.15.0
      - zipp==3.15.0
prefix: /home/alex/anaconda3/envs/smax
