"LR": 1e-3
"NUM_ENVS": 64
"NUM_STEPS": 300
"TOTAL_TIMESTEPS": 1e7
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 4
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.2
"ENT_COEF": 2e-6
"VF_COEF": 4.5
"MAX_GRAD_NORM": 0.5
"ACTIVATION": "tanh"
"SEED": 30
"ENV_NAME": "ant_4x2" 
"ENV_KWARGS": {}
"ANNEAL_LR": True
"DEVICE": 0
"DISABLE_JIT": False

# WandB Params
"ENTITY": "" 
"PROJECT": "jaxmarl-mabrax"
"WANDB_MODE": "disabled"