"LR": 5e-4
"NUM_ENVS": 16
"NUM_STEPS": 101
"HIDDEN_SIZE": 128
"TOTAL_TIMESTEPS": 1e7
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 2
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.3
"SCALE_CLIP_EPS": False
"ENT_COEF": 0.01
"VF_COEF": 1.0
"MAX_GRAD_NORM": 0.5
"ACTIVATION": "tanh"
"ANNEAL_LR": True
"SEED": 30
"NUM_SEEDS": 1

"ENV_NAME": "JaxRobotarium_navigation"
"ENV_KWARGS": {
  "num_agents": 3,
  "max_steps": 100,
  "action_type": "Discrete",
  "robotarium": {
    "number_of_robots": 3,
    "show_figure": False,
    "sim_in_real_time": False,
  },
  "controller": {
    "controller": "clf_uni_position",
    "barrier_fn": "robust_barriers",
  },
  "update_frequency": 30
}

# evaluate
"TEST_DURING_TRAINING": True
"TEST_INTERVAL": 0.05 # as a fraction of updates, i.e. log every 5% of training process
"TEST_NUM_STEPS": 101
"NUM_TEST_ENVS": 64 # number of episodes to average over, can affect performance

# WandB Params
"WANDB_MODE": "disabled"
"ENTITY": ""
"PROJECT": ""