# experiment params
"NUM_SEEDS": 2
"SEED": 0

# wandb params
"ENTITY": "mttga"
"PROJECT": "smax"
"WANDB_MODE": "online"

# where to save the params (if None, will not save)
"SAVE_PATH": "baselines/QLearning/checkpoints"