# experiment params
"NUM_SEEDS": 2
"SEED": 30

# wandb params
"ENTITY": ""
"PROJECT": "jaxMARL"
"WANDB_MODE": "disabled"

# where to save the params (if None, will not save)
"SAVE_PATH": "baselines/QLearning/checkpoints"