"NUM_ENVS": 8
"NUM_STEPS": 128
"BUFFER_SIZE": 3000
"BUFFER_BATCH_SIZE": 32
"TOTAL_TIMESTEPS": 20000000
"AGENT_HIDDEN_DIM": 256
"AGENT_INIT_SCALE": 1.
"PARAMETERS_SHARING": True
"EPSILON_START": 1.0
"EPSILON_FINISH": 0.05
"EPSILON_ANNEAL_TIME": 100000
"MAX_GRAD_NORM": 10
"TARGET_UPDATE_INTERVAL": 200
"LR": 0.001
"LR_LINEAR_DECAY": False
"EPS_ADAM": 0.00001
"TD_LAMBDA_LOSS": True
"TD_LAMBDA": 0.6
"GAMMA": 0.99
"VERBOSE": False
"WANDB_ONLINE_REPORT": True
"NUM_TEST_EPISODES": 32
"TEST_INTERVAL": 100000
