# valid for iql, vdn, qmix
"TOTAL_TIMESTEPS": 3e6
"NUM_ENVS": 8
"NUM_STEPS": 101
"BUFFER_SIZE": 5000
"BUFFER_BATCH_SIZE": 32
"HIDDEN_SIZE": 256
"MIXER_EMBEDDING_DIM": 32 # just for qmix
"MIXER_HYPERNET_HIDDEN_DIM": 128 # just for qmix
"MIXER_INIT_SCALE": 0.001 # just for qmix
"EPS_START": 1.0
"EPS_FINISH": 0.05
"EPS_DECAY": 0.1 # percentage of updates
"MAX_GRAD_NORM": 25
"TARGET_UPDATE_INTERVAL": 200
"TAU": 1.
"NUM_EPOCHS": 1 
"LR": 0.005
"LEARNING_STARTS": 10000 # timesteps
"LR_LINEAR_DECAY": True
"GAMMA": 0.9

# ENV
"ENV_NAME": "JaxRobotarium_navigation"
"ENV_KWARGS": {
  "num_agents": 3,
  "max_steps": 100,
  "action_type": "Discrete",
  "robotarium": {
    "number_of_robots": 3,
    "show_figure": False,
    "sim_in_real_time": False,
  },
  "controller": {
    "controller": "clf_uni_position",
    "barrier_fn": "robust_barriers",
  },
  "update_frequency": 30
}

# evaluate
"TEST_DURING_TRAINING": True
"TEST_INTERVAL": 0.05 # as a fraction of updates, i.e. log every 5% of training process
"TEST_NUM_STEPS": 101
"TEST_NUM_ENVS": 64 # number of episodes to average over, can affect performance

"LOG_AGENTS_SEPARATELY": True # iql will log indipendent agents separately